document.body.insertAdjacentHTML('beforeend',`<section class="audiences" id="audiences">
  <div class="section-wrap audiences-inner reveal">
    <div class="audience-head"><div><div class="section-kicker">Who We Work With</div><h2 class="section-title">Built for Both Sides of Growth.</h2></div><p class="section-copy">NOAH creates a connected environment where brands can find efficient growth and partners can turn reach, audience, and influence into opportunity.</p></div>
    <div class="audience-stage">
      <article class="audience-panel brand-side"><div><div class="audience-tag">For Brands</div><h3>Acquire More Customers.<br>Grow Revenue More Efficiently.</h3><p>Activate media, partner distribution, owned commerce, and performance intelligence through one coordinated growth model.</p><div class="audience-points"><span>Customer Acquisition</span><span>Revenue Growth</span><span>Market Expansion</span><span>Partner Activation</span><span>Performance Visibility</span></div><a class="audience-link" href="#contact">Grow With NOAH →</a></div><div class="audience-visual"></div></article>
      <article class="audience-panel partner-side"><div><div class="audience-tag">For Partners</div><h3>Turn Audience and Influence<br>Into Opportunity.</h3><p>Connect with brands, campaigns, commerce opportunities, and performance-led programs across the NOAH ecosystem.</p><div class="audience-points"><span>Brand Opportunities</span><span>Campaign Access</span><span>Commerce Activation</span><span>Monetization</span><span>Long-Term Partnerships</span></div><a class="audience-link" href="#contact">Partner With NOAH →</a></div><div class="audience-visual"></div></article>
    </div>
  </div>
</section>
<section class="network" id="network">
  <div class="section-wrap network-inner reveal">
    <div class="network-head"><div><div class="section-kicker">Our Network</div><h2 class="section-title">Distribution You Can Activate.</h2></div><p class="section-copy">NOAH combines partner-driven distribution with owned commerce destinations, creating more ways for brands to reach high-intent consumers and more opportunities for partners to participate in growth.</p></div>
    <div class="network-layout">
      <article class="partner-network"><h3>Partner Network</h3><p>Activate publishers, creators, affiliates, content partners, and performance-based distribution around growth opportunities.</p><div class="network-map"><div class="network-ring"></div><div class="network-ring r2"></div><div class="network-hub">NOAH<br>NETWORK</div><span class="network-chip nc1">Publishers</span><span class="network-chip nc2">Creators</span><span class="network-chip nc3">Affiliates</span><span class="network-chip nc4">Content Partners</span><span class="network-chip nc5">Distribution</span></div></article>
      <div class="properties">
        <article class="property"><div class="property-copy"><small>NOAH-Owned Commerce</small><h3>DealsCanvas</h3><p>A NOAH-owned commerce destination designed to connect consumers with relevant offers and shopping opportunities.</p><a class="text-link" href="https://www.dealscanvas.com/" target="_blank" rel="noopener">Visit DealsCanvas <span>↗</span></a></div><div class="browser-card"><div class="browser-bar"><i class="browser-dot"></i><i class="browser-dot"></i><i class="browser-dot"></i></div><div class="commerce-canvas"><div class="commerce-hero"></div><div class="commerce-line"></div><div class="commerce-line short"></div><div class="commerce-grid"><i class="commerce-tile"></i><i class="commerce-tile"></i><i class="commerce-tile"></i></div></div></div></article>
        <article class="property"><div class="property-copy"><small>NOAH-Owned Commerce</small><h3>CatchTheDeal.ai</h3><p>A NOAH-owned commerce experience focused on helping consumers discover timely, high-intent opportunities.</p><a class="text-link" href="https://www.catchthedeal.ai/" target="_blank" rel="noopener">Visit CatchTheDeal.ai <span>↗</span></a></div><div class="browser-card"><div class="browser-bar"><i class="browser-dot"></i><i class="browser-dot"></i><i class="browser-dot"></i></div><div class="commerce-canvas"><div class="commerce-hero"></div><div class="commerce-line"></div><div class="commerce-line short"></div><div class="commerce-grid"><i class="commerce-tile"></i><i class="commerce-tile"></i><i class="commerce-tile"></i></div></div></div></article>
      </div>
    </div>
  </div>
</section>`);
